### ISSUE TITLE
Overlay Network fails to publish ports

### ISSUE THREAD

**Issue by j0nathanr** [newsnowlabs/docker-ingress-routing-daemon#28]
Much thanks for releasing this to the public, I've successfully installed and configured the deamon and am recieving real client IPs to my services.

The only issue I'm having is the overlay network not publishing the container ports when the service is recreated. It's a bit strange as one ore two nodes may have the ports published but the remaing don't includiong the node that the container is running on. Sometimes none will have the ports published at all. I have verified the service\container is running and ports are stated as published. If I rerun the installer with my node IPs and services then recreate the service, all ports are published on all nodes. However, scaling the service to 0 then 1, fails to publish the ports again. 

Is this is known issue or intentional? Without the overlay network functioning it sort of defeats the purpose of getting real client IPs.

**Comment by struanb** [comment]
Hi @j0nathanr. Thanks for using the ingress routing daemon, and apologies for the long delay in getting back to you on this issue. We have been affected by illness in our team.

This definitely not a known issue nor intentional. We are using the ingress routing daemon in production at NewsNow and have experienced no such issues on scaling services down or up.

Can you tell me more about your set up?

What do you mean by 'failing to publish the ports', and how are you determining that some nodes have the port published but some don't?

Have you tried looking at the logs? It should be apparent, when containers are started, that the container networking is being reconfigured.

**Comment by struanb** [comment]
Closing due to lack of issue specificity or response.
