### ISSUE TITLE
Trying to run it without swarm (standalone docker containers not getting real remote IP address)

### ISSUE THREAD

**Issue by GcmMiguel** [newsnowlabs/docker-ingress-routing-daemon#5]
Hi there @struanb ,

I have been working with your solution for a couple of days and I really liked it, but it is not fitting with one of my issues. I am sorry for using the Issues tab for this but I believe this idea will help a lot of people using dockers.

The issue: I have a custom container that is listening port 80 for HTTP requests. The problem is that real IP is going to other headers such as X-Real-IP or X-Forwarded*. The problem is that this container is behind an NGINX reverse proxy, so it never receives the real IP address, and $remote_addr is pointing to nginx's IP address.

I tried to "reduce" the case included in your tool by isolating all requests to docker swarm (as I said I am working only with 1 certain docker, not a docker service or a swarm), by doing the proper calls to iptables and trying to set TOS to my case, but I had no chance, but I thought it should be very easy to bring this solution you created for swarm to single containers.

Do you think is it possible to use your solution for grabbing real IP addresses in single containers? 

Thank you! Nice work!

edit: as I read you had issues with notifications on GitHub, I mentioned on it :)

**Comment by struanb** [comment]
Hi @GcmMiguel, and thanks for trying out DIRD.

If I understand your case correctly, you are running a single independent docker container that is publishing an HTTP service on port 80, but that is not part of a swarm service.

Assuming so, the first thing to say is that DIRD is specifically intended to address the use of docker swarm services to publish TCP or UDP services load-balanced across one or more containers, and DIRD's internal workings are intimately tied to the internal workings of how docker uses IPVS within a swarm service for load-balancing incoming requests among multiple containers. Unlike a reverse proxy which is a TCP-layer load balancer, IPVS is a IP-layer load balancer which means the application containers can indeed see the client IP when DIRD is running and SNAT masquerade is disabled.

The second thing I would say is that, with standalone containers, it is not normally a problem to obtain the client's IP address via $remote_addr, as long as incoming HTTP requests arrive directly at the standalone container's published port.

Yet in your example, it sounds like this is not the case: your NGINX reverse proxy is instead the endpoint for those incoming HTTP requests, so _only it_ can identify the client IP address. As a reverse proxy, NGINX will be making its own independent HTTP connection to your standalone container, and having NGINX passing them onto an application using X-Real-IP or X-Forwarded-For are really the only available approaches as far as I can see.

As far as I can see, you have these options:
1. Reconfigure your container application to obtain the client IP from X-Real-IP or X-Forwarded-For instead of from $remote_addr
2. Remove the NGINX reverse proxy from your stack, and arrange for incoming HTTP requests to reach your container directly
3. Remove the NGINX reverse proxy from your stack, and relaunch your standalone container as a docker swarm service with one replica - or more replicas if you need to distribute and balance load - using DIRD to ensure the client IPs are visible to those service containers.

So the TL;DR summary is this: it's not possible for an application container to obtain the real IP of a client via $remote_addr, if there is reverse proxy between the client and the application container; either configure your reverse proxy to use X-Real-IP/X-Forwarded-For and configure your application accordingly, or remove the reverse proxy.

I hope this helps. As this isn't an issue for DIRD, I will be closing this issue.
