### ISSUE TITLE
Consider `--install-here`

### ISSUE THREAD

**Issue by alexanderadam** [newsnowlabs/docker-ingress-routing-daemon#9]
Maybe instead of firstly running `docker-ingress-routing-daemon` to get the network IPs and then pasting that exact IPs to `docker-ingress-routing-daemon --ingress-gateway-ips <Node Ingress IP List> --install` a `docker-ingress-routing-daemon --install-here` command could be used (that would simply use the IPs automatically).
Or rather not? :thinking: 
Am I missing something?

**Comment by struanb** [comment]
I think one of us must be missing something. Here's my thinking:

- For a node running a service container to route traffic back to the correct load balancer, DIND must be launched on that node with `--ingress-gateway-ip` specifying a list of all the ingress networks IPs of those load balancer nodes. This is so that, when it detects an eligible container is launched, it can create separate routing rules referencing each of these IPs.
- It's not possible to query these IPs from any one node. That's why it's necessary to run DIND without arguments on each load balancer node, and collate the IP addresses printed.
- A `--install-here` option could therefore only work in the limited use-case that DIND is to be run on one node only, that node serving as load balancer _and_ running service containers.
- This option could easily be added, but it would generally only help people running DIND on a one-node test swarm.

Let me know if this makes sense, or if I've misunderstood your suggestion.

**Comment by alexanderadam** [comment]
Ah, makes sense. Thank you for your perfect explanations! :pray:
